apiVersion: v1
kind: Service
metadata:
  name: fraud-detect-svc
spec:
  serviceAccountName: fraud-detect-sa
  selector:
    app: fraud-detect
    version: 1.0.0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP