server:
  shutdown: GRACEFUL

spring:
  profiles:
    active: local
management:
  endpoint:
    health:
      probes:
        enabled: true   # 开启 readiness / liveness 探针支持
  endpoints:
    web:
      exposure:
        include: health